// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.flydean17.protobuf;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.flydean17.protobuf.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   * @return Whether the age field is set.
   */
  boolean hasAge();
  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>string name = 2;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
