// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.flydean17.protobuf;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flydean17_protobuf_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flydean17_protobuf_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\026com.flydean17.protobuf\"" +
      "?\n\007Student\022\020\n\003age\030\001 \001(\005H\000\210\001\001\022\021\n\004name\030\002 \001" +
      "(\tH\001\210\001\001B\006\n\004_ageB\007\n\005_nameB\032\n\026com.flydean1" +
      "7.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_flydean17_protobuf_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_flydean17_protobuf_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flydean17_protobuf_Student_descriptor,
        new java.lang.String[] { "Age", "Name", "Age", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
